/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.siscom.view;

import br.com.siscom.acessorios.Calculadora;
import br.com.siscom.acessorios.Calendario;
import br.com.siscom.beans.NivelAcesso;
import br.com.siscom.view.compras.ConfirmaCotacaoCompra;
import br.com.siscom.view.compras.CotacaoCompra;
import br.com.siscom.view.compras.PedidoCompra;
import br.com.siscom.view.compras.RequisicaoCompra;
import br.com.siscom.view.estoque.AjustePrecos;
import br.com.siscom.view.estoque.EntradaProduto;

import br.com.siscom.view.financeiro.Pagamentos;
import br.com.siscom.view.financeiro.Recebimentos;
import java.beans.Beans;
import java.net.URL;
import java.util.List;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author pablicio
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }
    private HelpSet hs;
    private HelpBroker hb;
    private URL hsURL;

    public void openHelp() {
        String pathToHS = "/appwithhelp/docs/appwithhelp-hs.xml";
        try {
            hsURL = getClass().getResource(pathToHS);
            System.out.println(hsURL);
            hs = new HelpSet(null, hsURL);
        } catch (Exception e) {
            System.out.println("HelpSet" + e.getMessage());
            System.out.println("HelpSet" + pathToHS + " não encontrado");

        }
        hb = hs.createHelpBroker();
        hb.setDisplayed(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("siscomrefatorado?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT n FROM NivelAcesso n");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : query.getResultList();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Siscom - Sistema Comercial");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(231, 231, 255));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setToolTipText("Estoque");
        jPanel3.setLayout(new java.awt.GridLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/cliente32x32.png"))); // NOI18N
        jButton1.setToolTipText("Cadastro de Clientes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/fornecedor32x32.png"))); // NOI18N
        jButton3.setToolTipText("Cadastro de Fornecedores");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/estoque32x32.png"))); // NOI18N
        jButton2.setToolTipText("Estoque");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton16.setBackground(new java.awt.Color(255, 255, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/vendas32x32.png"))); // NOI18N
        jButton16.setToolTipText("Vendas");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton16);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/compras32x32.png"))); // NOI18N
        jButton4.setToolTipText("Compras");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        jButton20.setBackground(new java.awt.Color(255, 255, 255));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/orçamento32x32.png"))); // NOI18N
        jButton20.setToolTipText("Orçamento");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton20);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/serviço32x32.png"))); // NOI18N
        jButton5.setToolTipText("Configurações");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);

        jButton19.setBackground(new java.awt.Color(255, 255, 255));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/receber32x32.png"))); // NOI18N
        jPanel3.add(jButton19);

        jButton18.setBackground(new java.awt.Color(255, 255, 255));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/Ayuda.png"))); // NOI18N
        jButton18.setToolTipText("Ajuda");
        jPanel3.add(jButton18);

        jButton17.setBackground(new java.awt.Color(255, 255, 255));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/sair32x32.png"))); // NOI18N
        jButton17.setToolTipText("Sair");
        jPanel3.add(jButton17);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 352, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/Reservas.png"))); // NOI18N
        jMenu1.setText("Cadastro");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/cliente16x16.png"))); // NOI18N
        jMenuItem1.setText("Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/fornecedor16x16.png"))); // NOI18N
        jMenuItem3.setText("Fornecedores");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/bank.png"))); // NOI18N
        jMenuItem2.setText("Contas Bancárias");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/medida.png"))); // NOI18N
        jMenuItem4.setText("Unidades");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/estoque16X16.png"))); // NOI18N
        jMenuItem5.setText("Produtos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator2);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/salir.gif"))); // NOI18N
        jMenuItem6.setText("Departamentos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/funcionario.png"))); // NOI18N
        jMenuItem7.setText("Funcionários");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);
        jMenu1.add(jSeparator3);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/cartao.png"))); // NOI18N
        jMenuItem8.setText("Cartões");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/6199_16x16.png"))); // NOI18N
        jMenuItem12.setText("Plano de Contas");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/pgto.png"))); // NOI18N
        jMenuItem13.setText("Tipo de Pgto/Rcbto");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/sair16x16.png"))); // NOI18N
        jMenuItem14.setText("Sair");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem14);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/caixa32x32.png"))); // NOI18N
        jMenu2.setText("Movimento");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/pagar16X16.png"))); // NOI18N
        jMenuItem9.setText("Contas a Pagar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/receber16x16.png"))); // NOI18N
        jMenuItem10.setText("Contas a Receber");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/vendas16x16.png"))); // NOI18N
        jMenuItem11.setText("Vendas");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/orçamento16x16.png"))); // NOI18N
        jMenuItem29.setText("Orçamentos");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem29);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/estoque16X16.png"))); // NOI18N
        jMenu6.setText("Controle de Estoque");

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/nf.png"))); // NOI18N
        jMenuItem15.setText("Entrada de NF");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem15);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/preço.png"))); // NOI18N
        jMenuItem16.setText("Atualização de Preços");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem16);

        jMenu2.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/compras16x16.png"))); // NOI18N
        jMenu7.setText("Compras");

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/req.png"))); // NOI18N
        jMenuItem17.setText("Requisição");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem17);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/cot.png"))); // NOI18N
        jMenuItem18.setText("Cotação");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem18);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/confcot.png"))); // NOI18N
        jMenuItem19.setText("Confirma Cotação");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem19);

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/compras16x16.png"))); // NOI18N
        jMenuItem20.setText("Pedido");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem20);

        jMenu2.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/tesouraria.png"))); // NOI18N
        jMenu8.setText("Tesouraria e Banco");

        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/cheque-icon.png"))); // NOI18N
        jMenuItem21.setText("Emissão de Cheques");
        jMenu8.add(jMenuItem21);

        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/conc.png"))); // NOI18N
        jMenuItem22.setText("Conciliaçao de Cheques");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem22);

        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/caixa16x16.png"))); // NOI18N
        jMenuItem23.setText("Movimento de Banco");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem23);

        jMenu2.add(jMenu8);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/relatorio32x32.png"))); // NOI18N
        jMenu3.setText("Utilitários");

        jMenuItem24.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/8396_16x16.png"))); // NOI18N
        jMenuItem24.setText("Calculadora");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem24);

        jMenuItem25.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/8397_16x16.png"))); // NOI18N
        jMenuItem25.setText("Calendário");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem25);
        jMenu3.add(jSeparator4);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/7586_16x16.png"))); // NOI18N
        jMenu9.setText("Sistema de Segurança");

        jMenuItem27.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMenuItem27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/6086_16x16.png"))); // NOI18N
        jMenuItem27.setText("Trocar Senha Corrente");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem27);

        jMenuItem30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/7678_16x16.png"))); // NOI18N
        jMenuItem30.setText("Nível de Acesso");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem30);

        jMenu3.add(jMenu9);

        jMenuBar1.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/ajuda32.png"))); // NOI18N
        jMenu5.setText("Ajuda");

        jMenuItem26.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/1979_16x16.png"))); // NOI18N
        jMenuItem26.setText("Sobre o Sistema");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem26);

        jMenuItem28.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscom/imagens/ajuda_16x16.png"))); // NOI18N
        jMenuItem28.setText("Ajuda");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem28);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1106, 1106, 1106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(824, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        if (verificaAcesso(jMenuItem2.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Cadastro de Contas";
            BancoView.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }


    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed

        if (verificaAcesso(jMenuItem8.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Cadastro de Contas";
            CartaoView.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed

        if (verificaAcesso(jMenuItem13.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Cadastro de Contas";
            TipoPgtoView.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        /*String args[] = new String[1];
        args[0] = "Cadastro de Clientes";
        ClienteView.main(args);*/

        if (verificaAcesso(jMenuItem1.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Cadastro de Clientes";
            ClienteView.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private boolean verificaAcesso(String nomeMenu, String codFuncionario) {
        query = entityManager.createNamedQuery("NivelAcesso.verifiqueAcesso");
        query.setParameter("codFuncionario", Integer.parseInt(codFuncionario));
        query.setParameter("nomeModulo", nomeMenu);
        List<NivelAcesso> data = query.getResultList();
        if (data.size() > 0) {
            return true;
        } else {
            return false;
        }
    }
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        if (verificaAcesso(jMenuItem3.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Cadastro de Fornecedores";
            FornecedorView.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        if (verificaAcesso(jMenuItem5.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Cadastro de Produtos";
            ProdutoView.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        if (verificaAcesso(jMenuItem4.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Cadastro de Unidades";
            UnidadeView.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed

        if (verificaAcesso(jMenuItem12.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Cadastro de Planos de Contas";
            PlanoContaView.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        if (verificaAcesso(jMenuItem6.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Cadastro de Departamentos";
            DepartamentoView.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

        if (verificaAcesso(jMenuItem7.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Cadastro de Funcionários";
            FuncionarioView.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed

        if (verificaAcesso(jMenuItem11.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Movimento - Vendas";
            MovimentooVenda.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed

        if (verificaAcesso(jMenuItem29.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Movimento - Orçamentos";
            MovimrntoOrcamentoVenda.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed

        if (verificaAcesso(jMenuItem18.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Movimento - Cotação";
            CotacaoCompra.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed

        if (verificaAcesso(jMenuItem19.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Movimento - Confirma Cotação";
            ConfirmaCotacaoCompra.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed

        if (verificaAcesso(jMenuItem20.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Movimento - Pedidos";
            PedidoCompra.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed

        if (verificaAcesso(jMenuItem17.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Movimento - Requisição";
            RequisicaoCompra.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed

        if (verificaAcesso(jMenuItem16.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Movimento - Ajuste de Preços";
            AjustePrecos.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed

        if (verificaAcesso(jMenuItem9.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Movimento - Pagamentos";
            Pagamentos.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed

        if (verificaAcesso(jMenuItem10.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Movimento - Recebimentos";
            Recebimentos.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed

        if (verificaAcesso(jMenuItem15.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Movimento - Entrada de Produtos";
            EntradaProduto.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed

        if (verificaAcesso(jMenuItem30.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "";
            Nivel.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed

        String args[] = new String[1];
        args[0] = "Conciliação";
        ConciliacaoView.main(args);

    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        String args[] = new String[1];
        args[0] = "Movimento Bancário";
        MovimentoView.main(args);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        String args[] = new String[1];
        args[0] = "Troca de Senhas";
        TrocaSenhaView.main(args);
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         if (verificaAcesso(jMenuItem17.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Movimento - Requisição";
            RequisicaoCompra.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
       if (verificaAcesso(jMenuItem29.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Movimento - Orçamentos";
            MovimrntoOrcamentoVenda.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        String args[] = new String[1];
        args[0] = "Calculadora";
        Calculadora.main(args);
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        String args[] = new String[1];
        args[0] = "Calendário";
        Calendario.main(args);
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        openHelp();
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        JOptionPane.showMessageDialog(null,"Sistema Comercial"
                + "\nThiago Pablício & Murilo Gustavo"
                + "\nVersão: 1.0.0.0.0 - 2016");
       // JOptionPane.showMessageDialog(jMenu1, hs, string, WIDTH, icon);
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (verificaAcesso(jMenuItem30.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "";
            Nivel.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
       
        if (verificaAcesso(jMenuItem11.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Movimento - Vendas";
            MovimentooVenda.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (verificaAcesso(jMenuItem1.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Cadastro de Clientes";
            ClienteView.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (verificaAcesso(jMenuItem3.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Cadastro de Fornecedores";
            FornecedorView.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if (verificaAcesso(jMenuItem15.getText(), jLabel1.getText())) {
            String args[] = new String[1];
            args[0] = "Movimento - Entrada de Produtos";
            EntradaProduto.main(args);
        } else {

            JOptionPane.showMessageDialog(null, "Você não tem acesso");

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
                jLabel1.setText(args[0]);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private static javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private java.util.List list;
    private javax.persistence.Query query;
    // End of variables declaration//GEN-END:variables
}
