/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.siscom.view;

import br.com.adilson.util.PrinterMatrix;
import br.com.siscom.beans.Cfop;
import br.com.siscom.beans.Cliente;
import br.com.siscom.beans.Conexao;
import br.com.siscom.beans.Funcionario;
import br.com.siscom.beans.Produto;
import br.com.siscom.beans.VendaDet;
import br.com.siscom.beans.VendaDetPK;
import java.awt.EventQueue;
import java.beans.Beans;
import java.io.File;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author pablicio
 */
public class MovimentooVenda extends JPanel {

    public MovimentooVenda() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("siscomrefatorado?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT V FROM VendaCab V");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        jTextField11 = new javax.swing.JTextField();
        tipoPgtoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM TipoPgto t");
        tipoPgtoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tipoPgtoQuery.getResultList();
        cartaoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cartao c");
        cartaoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cartaoQuery.getResultList();
        tipoPgtoListCellRenderer1 = new br.com.siscom.renderer.TipoPgtoListCellRenderer();
        cartaoListCellRenderer1 = new br.com.siscom.renderer.CartaoListCellRenderer();
        clienteQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cliente c");
        funcionarioQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Funcionario c");
        produtoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Produto p");
        cfopQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cfop c");
        jPanel1 = new javax.swing.JPanel();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        venda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        teste = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        detailScrollPane = new javax.swing.JScrollPane();
        detailTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        newDetailButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        deleteDetailButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        jTextField11.setText("jTextField11");

        tipoPgtoListCellRenderer1.setText("tipoPgtoListCellRenderer1");

        cartaoListCellRenderer1.setText("cartaoListCellRenderer1");

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cabeçalho"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        masterTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codVendaCab}"));
        columnBinding.setColumnName("Cod Venda Cab");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codCfop}"));
        columnBinding.setColumnName("Cod Cfop");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codCartao}"));
        columnBinding.setColumnName("Cod Cartao");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codTipoPgto}"));
        columnBinding.setColumnName("Cod Tipo Pgto");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codCliente}"));
        columnBinding.setColumnName("Cod Cliente");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codFuncionario}"));
        columnBinding.setColumnName("Cod Funcionario");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataVendaCab}"));
        columnBinding.setColumnName("Data Venda Cab");
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vlrVendaCab}"));
        columnBinding.setColumnName("Vlr Venda Cab");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descontoVendaCab}"));
        columnBinding.setColumnName("Desconto Venda Cab");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totalVendaCab}"));
        columnBinding.setColumnName("Total Venda Cab");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numParcelasVendaCab}"));
        columnBinding.setColumnName("Num Parcelas Venda Cab");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${priVencimentoVendaCab}"));
        columnBinding.setColumnName("Pri Vencimento Venda Cab");
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numNfVendaCab}"));
        columnBinding.setColumnName("Num Nf Venda Cab");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vendaDetPK.CodProduto}"));
        columnBinding.setColumnName("Cod Produtro");
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterScrollPane.setViewportView(masterTable);

        jPanel1.add(masterScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 147, 0, 7));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codVendaCab}"), venda, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(venda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, -1));

        jLabel1.setText("Código Venda:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codCliente}"), jTextField2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextField2.addFocusListener(formListener);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 45, -1));

        jLabel2.setText("Cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jTextField3.setBackground(new java.awt.Color(255, 255, 204));
        jTextField3.setFocusable(false);
        jTextField3.setOpaque(false);
        jTextField3.setSelectionColor(new java.awt.Color(255, 255, 204));
        jTextField3.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 205, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codFuncionario}"), jTextField4, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextField4.addFocusListener(formListener);
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 47, -1));

        jLabel3.setText("Funcionário:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jTextField5.setBackground(new java.awt.Color(255, 255, 204));
        jTextField5.setFocusable(false);
        jTextField5.setOpaque(false);
        jTextField5.setSelectionColor(new java.awt.Color(255, 255, 204));
        jTextField5.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 210, -1));

        jComboBox1.setRenderer(tipoPgtoListCellRenderer1);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tipoPgtoList, jComboBox1);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codTipoPgto}"), jComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 96, -1));

        jComboBox2.setRenderer(cartaoListCellRenderer1);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cartaoList, jComboBox2);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codCartao}"), jComboBox2, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 76, -1));

        jLabel4.setText("Tipo de Pagamento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel5.setText("Cartão:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codCfop}"), jTextField6, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextField6.addFocusListener(formListener);
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 50, -1));

        jLabel6.setText("CFOP:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, -1));

        jTextField7.setBackground(new java.awt.Color(255, 255, 204));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField7.setFocusable(false);
        jTextField7.setOpaque(false);
        jTextField7.setSelectionColor(new java.awt.Color(255, 255, 204));
        jTextField7.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 270, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.numNfVendaCab}"), teste, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(teste, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 54, -1));

        jLabel7.setText("N° Nota:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.numParcelasVendaCab}"), jTextField9, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 59, -1));

        jLabel8.setText("N° Parcelas:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel9.setText("Pri Vencimento:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jTextField12.setBackground(new java.awt.Color(255, 255, 204));
        jTextField12.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.vlrVendaCab}"), jTextField12, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 73, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.descontoVendaCab}"), jTextField13, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 70, -1));

        jTextField14.setBackground(new java.awt.Color(255, 255, 204));
        jTextField14.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.totalVendaCab}"), jTextField14, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 88, -1));

        jLabel10.setText("Valor:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jLabel11.setText("Desconto::");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        jLabel12.setText("Total:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        jLabel13.setText("Data:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.dataVendaCab}"), jFormattedTextField1, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 72, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.priVencimentoVendaCab}"), jFormattedTextField2, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 62, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${selectedElement.vendaDetList}");
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, eLProperty, detailTable);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vendaDetPK.codProduto}"));
        columnBinding.setColumnName("Código do Produto");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descricaoProduto}"));
        columnBinding.setColumnName("Descrição do Produto");
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${qtdeVendaDet}"));
        columnBinding.setColumnName("Qtde Venda Det");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vlrUnitVendaDet}"));
        columnBinding.setColumnName("Vlr Unit Venda Det");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vlrTotalVendaDet}"));
        columnBinding.setColumnName("Vlr Total Venda Det");
        columnBinding.setColumnClass(Double.class);
        jTableBinding.setSourceUnreadableValue(java.util.Collections.emptyList());
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        detailScrollPane.setViewportView(detailTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailScrollPane)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        saveButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\pablicio\\Documents\\essa\\Imagens\\confirmar.JPG")); // NOI18N
        saveButton.setText("      Confirmar");
        saveButton.addActionListener(formListener);

        refreshButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\pablicio\\Documents\\essa\\Imagens\\cancelar.JPG")); // NOI18N
        refreshButton.setText("         Cancelar");
        refreshButton.addActionListener(formListener);

        newDetailButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\pablicio\\Documents\\essa\\Imagens\\inserir.JPG")); // NOI18N
        newDetailButton.setText("     Inserir Item");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), newDetailButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        newDetailButton.addActionListener(formListener);

        newButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\pablicio\\Documents\\essa\\Imagens\\novo.JPG")); // NOI18N
        newButton.setText("    Nova Venda");
        newButton.addActionListener(formListener);

        deleteDetailButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\pablicio\\Documents\\essa\\Imagens\\excluir.JPG")); // NOI18N
        deleteDetailButton.setText("              Excluir");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, detailTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteDetailButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteDetailButton.addActionListener(formListener);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pablicio\\Documents\\essa\\Imagens\\acessar.JPG")); // NOI18N
        jButton1.setText(" Acessar Venda");
        jButton1.addActionListener(formListener);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\pablicio\\Documents\\essa\\Imagens\\imprimir.JPG")); // NOI18N
        jButton2.setText("         Imprimir ");
        jButton2.addActionListener(formListener);

        jButton3.setText("Calcula Total");
        jButton3.addActionListener(formListener);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(newButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteDetailButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newDetailButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(979, 979, 979))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteDetailButton)
                .addGap(18, 18, 18)
                .addComponent(newDetailButton)
                .addGap(18, 18, 18)
                .addComponent(refreshButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.FocusListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == saveButton) {
                MovimentooVenda.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == refreshButton) {
                MovimentooVenda.this.refreshButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newDetailButton) {
                MovimentooVenda.this.newDetailButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newButton) {
                MovimentooVenda.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == deleteDetailButton) {
                MovimentooVenda.this.deleteDetailButtonActionPerformed(evt);
            }
            else if (evt.getSource() == jButton1) {
                MovimentooVenda.this.jButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton2) {
                MovimentooVenda.this.jButton2ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton3) {
                MovimentooVenda.this.jButton3ActionPerformed(evt);
            }
        }

        public void focusGained(java.awt.event.FocusEvent evt) {
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
            if (evt.getSource() == jTextField2) {
                MovimentooVenda.this.jTextField2FocusLost(evt);
            }
            else if (evt.getSource() == jTextField4) {
                MovimentooVenda.this.jTextField4FocusLost(evt);
            }
            else if (evt.getSource() == jTextField6) {
                MovimentooVenda.this.jTextField6FocusLost(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents


    private void deleteDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDetailButtonActionPerformed
        int index = masterTable.getSelectedRow();
        br.com.siscom.beans.VendaCab V = list.get(masterTable.convertRowIndexToModel(index));
        Collection<br.com.siscom.beans.VendaDet> vs = V.getVendaDetList();
        int[] selected = detailTable.getSelectedRows();
        List<br.com.siscom.beans.VendaDet> toRemove = new ArrayList<br.com.siscom.beans.VendaDet>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            selected[idx] = detailTable.convertRowIndexToModel(selected[idx]);
            int count = 0;
            Iterator<br.com.siscom.beans.VendaDet> iter = vs.iterator();
            while (count++ < selected[idx]) {
                iter.next();
            }
            br.com.siscom.beans.VendaDet v = iter.next();
            toRemove.add(v);
            entityManager.remove(v);
        }
        vs.removeAll(toRemove);
        masterTable.clearSelection();
        masterTable.setRowSelectionInterval(index, index);
    }//GEN-LAST:event_deleteDetailButtonActionPerformed

    private void newDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDetailButtonActionPerformed
/*        entityManager.getTransaction().commit();
        entityManager.getTransaction().begin();

        int index = masterTable.getSelectedRow();
        br.com.siscom.beans.VendaCab V = list.get(masterTable.convertRowIndexToModel(index));
        Collection<br.com.siscom.beans.VendaDet> vs = V.getVendaDetList();
        if (vs == null) {
            vs = new LinkedList<br.com.siscom.beans.VendaDet>();
            V.setVendaDetList((List) vs);
        }
        br.com.siscom.beans.VendaDet v = new br.com.siscom.beans.VendaDet();

        VendaDetPK vpk = new VendaDetPK();
        vpk.setCodVendaCab(vpk.getCodVendaCab());
        v.setVendaDetPK(vpk);
        ImportaProduto ip = new ImportaProduto(null, true);
        ip.recebeObjeto(v);
        ip.setVisible(true);
        v.setVendaCab(V);

        produtoQuery = entityManager.createNamedQuery("Produto.findByCodProduto");
        produtoQuery.setParameter("codProduto", v.getVendaDetPK().getCodProduto());
        List<Produto> p = produtoQuery.getResultList();
        v.setDescricaoProduto(p.get(0).getDescricaoProduto());

        entityManager.persist(v);

        vs.add(v);
        masterTable.clearSelection();
        masterTable.setRowSelectionInterval(index, index);
        int row = vs.size() - 1;
        detailTable.setRowSelectionInterval(row, row);
        detailTable.scrollRectToVisible(detailTable.getCellRect(row, 0, true));*/

        entityManager.getTransaction().commit();
        entityManager.getTransaction().begin();

        int index = masterTable.getSelectedRow();
        br.com.siscom.beans.VendaCab V = list.get(masterTable.convertRowIndexToModel(index));
        Collection<br.com.siscom.beans.VendaDet> vs = V.getVendaDetList();
        if (vs == null) {
            vs = new LinkedList<br.com.siscom.beans.VendaDet>();
            V.setVendaDetList((List) vs);
        }
        br.com.siscom.beans.VendaDet v = new br.com.siscom.beans.VendaDet();
        VendaDetPK vpk = new VendaDetPK();

        vpk.setCodVendaCab(V.getCodVendaCab());
        v.setVendaDetPK(vpk);
        
        ImportaProduto ip = new ImportaProduto(null, true);
        ip.recebeObjeto(v);
        ip.setVisible(true);

        v.setVendaCab(V);

        produtoQuery = entityManager.createNamedQuery("Produto.findByCodProduto");
        produtoQuery.setParameter("codProduto", vpk.getCodProduto());
        List<Produto> data = produtoQuery.getResultList();
        v.setDescricaoProduto(data.get(0).getDescricaoProduto());
        
        entityManager.persist(v);
        vs.add(v);

        masterTable.clearSelection();
        masterTable.setRowSelectionInterval(index, index);
        int row = vs.size() - 1;
        detailTable.setRowSelectionInterval(row, row);
        detailTable.scrollRectToVisible(detailTable.getCellRect(row, 0, true));
    }//GEN-LAST:event_newDetailButtonActionPerformed

    @SuppressWarnings("unchecked")
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        br.com.siscom.beans.VendaCab V = new br.com.siscom.beans.VendaCab();
        entityManager.persist(V);
        list.add(V);
        int row = list.size() - 1;
        masterTable.setRowSelectionInterval(row, row);
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
        jTextField2.requestFocus();
        venda.setEnabled(false);
    }//GEN-LAST:event_newButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<br.com.siscom.beans.VendaCab> merged = new ArrayList<br.com.siscom.beans.VendaCab>(list.size());
            for (br.com.siscom.beans.VendaCab V : list) {
                merged.add(entityManager.merge(V));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_saveButtonActionPerformed
    private List<Cliente> listCliente;
    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        try {
            clienteQuery = entityManager.createNamedQuery("Cliente.findByCodCliente");
            clienteQuery.setParameter("codCliente", Integer.parseInt(jTextField2.getText()));
            listCliente = clienteQuery.getResultList();
            jTextField3.setText(listCliente.get(0).getNomeCliente());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro!");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private List<Funcionario> listFuncionario;
    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        try {
            funcionarioQuery = entityManager.createNamedQuery("Funcionario.findByCodFuncionario");
            funcionarioQuery.setParameter("codFuncionario", Integer.parseInt(jTextField4.getText()));
            listFuncionario = funcionarioQuery.getResultList();
            jTextField5.setText(listFuncionario.get(0).getNomeFuncionario());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro!");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextField4FocusLost

     private List<Cfop> listCfop;
    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
       
    try {
            cfopQuery = entityManager.createNamedQuery("Cfop.findByCodCfop");
            cfopQuery.setParameter("codCfop", Integer.parseInt(jTextField6.getText()));
            listCfop = cfopQuery.getResultList();
            jTextField7.setText(listCfop.get(0).getDescricaoCfop());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro!");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextField6FocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       /* Double valorTotal = 0.0;
        Double totalGeral = 0.0;
        
        
        int index = masterTable.getSelectedRow();
        br.com.siscom.beans.VendaCab V = list.get(masterTable.convertRowIndexToModel(index));
        Collection<br.com.siscom.beans.VendaDet> vs = V.getVendaDetList();
        
        for (VendaDet v : vs) {
            if (v.getQtdeVendaDet() == null) {
                v.setQtdeVendaDet(1);
            }
            v.setVlrTotalVendaDet(v.getVlrTotalVendaDet()*v.getQtdeVendaDet());
            
            valorTotal += v.getVlrTotalVendaDet();
        }
        
        if(jTextField13.getText().equals("")){
            jTextField13.setText("0");
        }
        totalGeral = valorTotal - Double.parseDouble(jTextField13.getSelectedText());
        jTextField12.setText(String.valueOf(valorTotal));
        jTextField14.setText(String.valueOf(totalGeral));*/
       
        Double valorTotal = 0.0;
    Double totalGeral = 0.0;
    
    int index = masterTable.getSelectedRow();
    br.com.siscom.beans.VendaCab V = list.get(masterTable.convertRowIndexToModel(index));
    Collection<br.com.siscom.beans.VendaDet> vs = V.getVendaDetList();
    
    for (VendaDet vendaDet : vs) {
        if (vendaDet.getQtdeVendaDet() == null) {
            vendaDet.setQtdeVendaDet(1);
        }
        vendaDet.setVlrTotalVendaDet(vendaDet.getVlrUnitVendaDet() * vendaDet.getQtdeVendaDet());
        valorTotal = valorTotal + vendaDet.getVlrTotalVendaDet();
    }
    
    if (jTextField13.getText().equals("")) {
        jTextField13.setText("0");
    }
    
    totalGeral = valorTotal - Double.parseDouble(jTextField13.getText());
    
    jTextField12.setText(String.valueOf(valorTotal));
    jTextField14.setText(String.valueOf(totalGeral));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         PrinterMatrix printer = new PrinterMatrix();

    //Define o tamanho do papel/tela para impressão, aqui 25 linhas e 80 colunas
    printer.setOutSize(43, 80);
    printer.printCharAtCol(1, 1, 80, "_");
    printer.printTextLinCol(2, 41, "X");

    //pegue o CNPJ da tabela de cadastro dos dados da empresa
    //no nosso caso esse numero será estatico - RUIM
    printer.printTextLinCol(4, 41, "01.325.654/0001-22");
    printer.printCharAtCol(1, 1, 80, "_");

    //descricao do CFOP
    printer.printTextLinCol(5, 3, teste.getText());
    //codigo CFOP
    printer.printTextLinCol(5, 30, jTextField7.getText());
    printer.printCharAtCol(1, 1, 80, "_");
    //dados do cliente
    printer.printTextLinCol(6, 3, jTextField3.getText());    
    //faça um if - se for "F" traz CPF, se for "J" traz CNPJ
    printer.printTextLinCol(6, 41, listCliente.get(0).getCpfCliente());

    //data de emissao
    printer.printTextLinCol(6, 55, jFormattedTextField1.getText());    
    
    int linha = 14;

    int index = masterTable.getSelectedRow();
    br.com.siscom.beans.VendaCab V = list.get(masterTable.convertRowIndexToModel(index));    
    Collection<br.com.siscom.beans.VendaDet> vs = V.getVendaDetList();    
    for (VendaDet vendaDet : vs) {

        printer.printTextLinCol(linha, 3, String.valueOf(vendaDet.getVendaDetPK().getCodProduto()));
        printer.printTextLinCol(linha, 15, String.valueOf(vendaDet.getDescricaoProduto()));
        printer.printTextLinCol(linha, 35, String.valueOf(vendaDet.getQtdeVendaDet()));
        printer.printTextLinCol(linha, 41, String.valueOf(vendaDet.getVlrUnitVendaDet()));
        printer.printTextLinCol(linha, 50, String.valueOf(vendaDet.getVlrTotalVendaDet()));
        
        linha++;

    }
    printer.printTextLinCol(26, 60, jTextField14.getText());
printer.printCharAtCol(1, 1, 80, "_");
    printer.toFile("impressao.txt");

    String arg[] = {""};
    ImpressaoView.main(arg);
    }//GEN-LAST:event_jButton2ActionPerformed
    private Connection connection = new Conexao().conectar();

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Map p = new  HashMap();
        p.put("ss", teste.getText());
        p.put("venda", venda.getText());
        try {
            System.out.println( new File("").getAbsolutePath());
            JasperReport  report = JasperCompileManager.compileReport("C:\\Users\\pablicio\\Documents\\essa\\br\\siscom\\src\\br\\com\\siscom\\relatorios\\NotaFiscal_1.jrxml");
            JasperPrint print = JasperFillManager.fillReport(report, p,connection);
            JasperViewer view = new JasperViewer(print, false);
            view.setTitle("Relatório de Bancos");
            view.setVisible(true);
            view.toFront();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<br.com.siscom.beans.Cartao> cartaoList;
    private br.com.siscom.renderer.CartaoListCellRenderer cartaoListCellRenderer1;
    private javax.persistence.Query cartaoQuery;
    private javax.persistence.Query cfopQuery;
    private javax.persistence.Query clienteQuery;
    private javax.swing.JButton deleteDetailButton;
    private javax.swing.JScrollPane detailScrollPane;
    private javax.swing.JTable detailTable;
    private javax.persistence.EntityManager entityManager;
    private javax.persistence.Query funcionarioQuery;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private java.util.List<br.com.siscom.beans.VendaCab> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton newButton;
    private javax.swing.JButton newDetailButton;
    private javax.persistence.Query produtoQuery;
    private javax.persistence.Query query;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField teste;
    private java.util.List<br.com.siscom.beans.TipoPgto> tipoPgtoList;
    private br.com.siscom.renderer.TipoPgtoListCellRenderer tipoPgtoListCellRenderer1;
    private javax.persistence.Query tipoPgtoQuery;
    private javax.swing.JTextField venda;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimentooVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimentooVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimentooVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimentooVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new MovimentooVenda());
                //frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
                frame.setTitle(args[0]);
                frame.setLocationRelativeTo(null);
            }
        });
    }

}
